{% set name = "HofstadterTools" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/HofstadterTools-{{ version }}.tar.gz
  sha256: 2ffe42706ef36218a80f38bcd59bfc96cb6ce893af6f3ebf6b5d4b533aabcd1e

build:
  entry_points:
    - band_structure = HT.band_structure:main
    - butterfly = HT.butterfly:main
    - plot_band_structure = HT.plot.plot_band_structure:main
    - plot_butterfly = HT.plot.plot_butterfly:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - numpy
    - matplotlib-base
    - prettytable
    - tqdm
    - pytest
    - ipython
    - jupyter
    - pyqt

test:
  commands:
    - pip check
    - pytest --pyargs HT
    - band_structure --help
    - butterfly --help
    - plot_band_structure --help
    - plot_butterfly --help
  requires:
    - pip
    - pytest

about:
  home: https://hofstadter.tools
  summary: A Python package for analyzing the Hofstadter model.
  description: HofstadterTools (HT) is a set of Python programs and classes for analyzing the Hofstadter model, which describes the behavior of non-interacting quantum particles hopping on a lattice coupled to a gauge field. This package can be used to compute the band structure of a generalized Hofstadter model on any regular Euclidean lattice, as well as its key properties, such as quantum geometry and topology.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://hofstadter.tools
  dev_url: https://github.com/HofstadterTools/HofstadterTools

extra:
  recipe-maintainers:
    - bartandrews
